# ASP.NET Core

trigger:
- main

pool: 
  vmImage: ubuntu-lasted

variables:
  buildConfiguration: 'Release'

steps:
- script: donet build --configuration $(buildConfiguration)
  displayName: 'donet build $(buildConfiguration)'